
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhksouubmomfegsoeltl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoa3NvdXVibW9tZmVnc29lbHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MzEzODgsImV4cCI6MjA1ODEwNzM4OH0.Ioe5LhALBvWTcGkE4og-ruJc9Epy3AjtC1A1qCCxg-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
